title: ðŸŒž
theme: jekyll-theme-modernist
description: by <a href="https://github.com/insanj">@insanj</a>
show_downloads: true
repository_url: https://github.com/insanj/supercharge
author:
  name: "Julian Weiss"
